---
services:
  pg-0:
    image: docker.io/bitnami/postgresql-repmgr:14
    volumes:
      - pg_0_data:/bitnami/postgresql
    networks:
      - psql_net
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=${POSTGRESQL_POSTGRES_PASSWORD}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=${POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS}
      - REPMGR_PRIMARY_HOST=${REPMGR_PRIMARY_HOST}
      - REPMGR_PARTNER_NODES=${REPMGR_PARTNER_NODES}
      - REPMGR_NODE_NAME=${REPMGR_NODE_NAME_0}
      - REPMGR_NODE_NETWORK_NAME=${REPMGR_NODE_NETWORK_NAME_0}
      - REPMGR_USERNAME=${REPMGR_USERNAME}
      - REPMGR_PASSWORD=${REPMGR_PASSWORD}

  pg-1:
    image: docker.io/bitnami/postgresql-repmgr:14
    volumes:
      - pg_1_data:/bitnami/postgresql
    networks:
      - psql_net
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=${POSTGRESQL_POSTGRES_PASSWORD}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=${POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS}
      - REPMGR_PRIMARY_HOST=${REPMGR_PRIMARY_HOST}
      - REPMGR_PARTNER_NODES=${REPMGR_PARTNER_NODES}
      - REPMGR_NODE_NAME=${REPMGR_NODE_NAME_1}
      - REPMGR_NODE_NETWORK_NAME=${REPMGR_NODE_NETWORK_NAME_1}
      - REPMGR_USERNAME=${REPMGR_USERNAME}
      - REPMGR_PASSWORD=${REPMGR_PASSWORD}
      - REPMGR_FAILOVER=${REPMGR_FAILOVER}

  pgpool:
    image: docker.io/bitnami/pgpool:4
    networks:
      - psql_net
    environment:
      - PGPOOL_BACKEND_NODES=${PGPOOL_BACKEND_NODES}
      - PGPOOL_SR_CHECK_USER=${PGPOOL_SR_CHECK_USER}
      - PGPOOL_SR_CHECK_PASSWORD=${PGPOOL_SR_CHECK_PASSWORD}
      - PGPOOL_ENABLE_LDAP=${PGPOOL_ENABLE_LDAP}
      - PGPOOL_POSTGRES_USERNAME=${PGPOOL_POSTGRES_USERNAME}
      - PGPOOL_POSTGRES_PASSWORD=${PGPOOL_POSTGRES_PASSWORD}
      - PGPOOL_ADMIN_USERNAME=${PGPOOL_ADMIN_USERNAME}
      - PGPOOL_ADMIN_PASSWORD=${PGPOOL_ADMIN_PASSWORD}
      - PGPOOL_ENABLE_LOAD_BALANCING=${PGPOOL_ENABLE_LOAD_BALANCING}
      - PGPOOL_POSTGRES_CUSTOM_USERS=${PGPOOL_POSTGRES_CUSTOM_USERS}
      - PGPOOL_POSTGRES_CUSTOM_PASSWORDS=${PGPOOL_POSTGRES_CUSTOM_PASSWORDS}
      - REPMGR_FAILOVER=${REPMGR_FAILOVER}
    depends_on:
      - pg-0
volumes:
  pg_0_data:
    driver: local
  pg_1_data:
    driver: local

networks:
  psql_net:
    name: psql_net
    driver: overlay
    external: false
    attachable: true
