image: 'docker:24.0.5'
.docker_login: &docker_login |
  docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

stages:
  - build

variables:
  VERSION: v1.0.0
  


build-worker:
  image: docker:24
  stage: build
  services:
    - docker:24-dind
  before_script:
    - *docker_login
  variables:
    TAG_COMMIT: $CI_REGISTRY_IMAGE/worker:${VERSION}
  script:
    - docker build -t $TAG_COMMIT -f ./voting-app/worker/Dockerfile ./voting-app/worker/
    - docker push $TAG_COMMIT
  tags:
    - my-runner
#####################

build-vote:
  image: docker:24
  stage: build
  services:
    - docker:24-dind
  before_script:
    - *docker_login
  variables:
    TAG_COMMIT: $CI_REGISTRY_IMAGE/vote:${VERSION}
  script:
    - docker build -t $TAG_COMMIT -f ./voting-app/vote/Dockerfile ./voting-app/vote/
    - docker push $TAG_COMMIT
  tags:
    - my-runner
##################################

build-result:
  image: docker:24
  stage: build
  services:
    - docker:24-dind
  before_script:
    - *docker_login
  variables:
    TAG_COMMIT: $CI_REGISTRY_IMAGE/result:${VERSION}
  script:
    - docker build -t $TAG_COMMIT -f ./voting-app/result/Dockerfile ./voting-app/result/
    - docker push $TAG_COMMIT
  tags:
    - my-runner


##################################

deploy:
  stage: deploy
  variables:
    TAG_COMMIT: $CI_REGISTRY_IMAGE
    DEPLOY_PATH: '/opt/DecisionDeck'
    SSH: '-o StrictHostKeyChecking=no user@ip'
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - |
        ssh $SSH "
          docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
          cd $DEPLOY_PATH
          docker-compose  pull
          docker-compose  down
          docker-compose up -d
          docker system prune -a --force
        "
  tags:
    - my-runner
