---
services:
  vote:
    build: 
      context: ./vote
      target: dev
    volumes:
     - ./vote:/usr/local/app
    networks:
      - redis_net
      - app_net
    command: python app.py
    labels:
        - "traefik.enable=true"
        - "traefik.docker.network=app_net"
        - "traefik.http.routers.vote.entrypoints=http"
        - "traefik.http.routers.vote.rule=Host(`app.web.echoamir.ir`)"
        - "traefik.http.routers.vote.middlewares=https-redirect"
        - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.vote-secure.entrypoints=https"
        - "traefik.http.routers.vote-secure.rule=Host(`app.web.echoamir.ir`)"
        - "traefik.http.routers.vote-secure.tls=true"
        - "traefik.http.routers.vote-secure.tls.certresolver=mycert"
        - "traefik.http.routers.vote-secure.service=vote"
        - "traefik.http.services.vote.loadbalancer.server.port=80"


  result:
    build: ./result
    entrypoint: nodemon --inspect=0.0.0.0 server.js
    networks:
      - psql_net
      - app_net
    labels:
        - "traefik.enable=true"
        - "traefik.docker.network=app_net"
        - "traefik.http.routers.result.entrypoints=http"
        - "traefik.http.routers.result.rule=Host(`result.web.echoamir.ir`)"
        - "traefik.http.routers.result.middlewares=https-redirect"
        - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.result-secure.entrypoints=https"
        - "traefik.http.routers.result-secure.rule=Host(`result.web.echoamir.ir`)"
        - "traefik.http.routers.result-secure.tls=true"
        - "traefik.http.routers.result-secure.tls.certresolver=mycert"
        - "traefik.http.routers.result-secure.service=result"
        - "traefik.http.services.result.loadbalancer.server.port=80"


  worker:
    build:
      context: ./worker
    networks:
      - redis_net
      - psql_net
      - app_net

volumes:
  db-data:

networks:
  redis_net:
    external: true
    driver: overlay
    attachable: true
  psql_net:
    external: true
    driver: overlay
    attachable: true
  app_net:
    external: true
    driver: overlay
    attachable: true
